[book]
authors = ["(Wasiu Yusuf)"]
language = "en"
multilingual = false
src = "src"
title = "Web Foundations - Try Kibo 6"

[build]
build-dir = "output"
create-missing = false
use-default-preprocessors = false
